### ISSUE TITLE
Reformat dates in metadata

### ISSUE THREAD

**Issue by wtbarnes** [wtbarnes/resume#7]
Dates data should be independent of representation. List dates as day, month, year. Add filters for different representations.

E.g.

- `dd/mm/yyyy`
- `dd/mm/yy`
- `mm/dd/yy`
- `mm(full) yyyy`
- `mm(abbr.) yyyy`

**Comment by wtbarnes** [comment]
I've added a filter and fixed some of the dates. However, many of them still need to be updated. The format that I've followed is:

```yaml
dates:
  start:
    day: 
    month:
    year:
  end:
    day:
    month:
    year:
```
